# Generated by Django 2.2.1 on 2020-09-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(default='null', max_length=250)),
                ('user', models.CharField(default='null', max_length=250)),
            ],
        ),
    ]
