# Generated by Django 2.2.1 on 2020-09-18 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='event',
        ),
    ]
