# Generated by Django 2.2.1 on 2020-09-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_remove_pipeline_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='event',
            field=models.CharField(default='null', max_length=250),
        ),
    ]
