# Generated by Django 2.2.1 on 2020-09-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_auto_20200918_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='user',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='event',
            field=models.CharField(default='+', max_length=250),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='youtube',
            field=models.CharField(default='+', max_length=250),
        ),
    ]
