# Generated by Django 2.2.1 on 2020-09-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0005_auto_20200924_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipeline',
            old_name='youtube',
            new_name='category',
        ),
        migrations.AddField(
            model_name='pipeline',
            name='date_added',
            field=models.CharField(default='+', max_length=250),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='date_of_event',
            field=models.CharField(default='+', max_length=250),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='significance',
            field=models.CharField(default='+', max_length=250),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='source_other',
            field=models.CharField(default='+', max_length=250),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='source_twitter',
            field=models.CharField(default='+', max_length=250),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='source_youtube',
            field=models.CharField(default='+', max_length=250),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='sub_category',
            field=models.CharField(default='+', max_length=250),
        ),
    ]
