# Generated by Django 2.2.1 on 2020-09-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0007_auto_20200924_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='source_other',
            field=models.CharField(default='false', max_length=250),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='source_twitter',
            field=models.CharField(default='false', max_length=250),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='source_youtube',
            field=models.CharField(default='false', max_length=250),
        ),
    ]
